[versions]
agp = "8.7.1"
kotlin = "1.9.24"
coreKtx = "1.13.1"
appcompat = "1.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

